[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vista-sr"
version = "0.1.0"
description = "VisTA-SR: Improving the Accuracy and Resolution of Low-Cost Thermal Imaging Cameras for Agriculture (CVPRW 2024)"
readme = "README.md"
authors = [
  { name = "Heesup Yun", email = "hspyun@ucdavis.edu" }
]
license = { text = "Apache-2.0" }
dependencies = [
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "opencv-python>=4.7.0",
    "numpy>=1.24.0",
    "scipy>=1.10.0",
    "Pillow>=9.4.0",
    "tqdm>=4.65.0",
    "PyYAML>=6.0",
    "natsort>=8.3.0"
]

[project.urls]
"Homepage" = "https://github.com/heesup/VisTA-SR"
"Paper" = "https://openaccess.thecvf.com/content/CVPR2024W/Vision4Ag/papers/Yun_VisTA-SR_Improving_the_Accuracy_and_Resolution_of_Low-Cost_Thermal_Imaging_CVPRW_2024_paper.pdf"
"Dataset" = "https://huggingface.co/datasets/heesup/VisTA-SR"
